name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: safelink-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - run: npm i -g gulp-cli ts-node typescript npm
        name: install global packages
      - run: yarn install
        name: clean install
      - run: yarn build
        name: build package
      - run: gulp copy
