name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: safelink-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - run: npm i -g gulp-cli ts-node typescript npm
        name: install global packages
      - run: npm install
        name: clean install
      - run: npm run build
        name: build package
      - run: gulp copy
      - name: Commits
        if: runner.os == 'Linux'
        continue-on-error: true
        shell: bash
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dist release
          date=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "Build $(date)"
          git push -u origin master
